export const environment = {
  production: true,
  debug: false,
  firebaseConfig: {
    apiKey: 'AIzaSyAnLbmH1fibqkFZ2nG3c4qgeNy1UQ4aG-8',
    authDomain: 'dyspo-2bb43.firebaseapp.com',
    projectId: 'dyspo-2bb43',
    storageBucket: 'dyspo-2bb43.appspot.com',
    messagingSenderId: '1017972190269',
    appId: '1:1017972190269:web:40584190abc557bcae0e54',
    measurementId: 'G-YH273CTJLR',
  },
  DEFAULT_AVATAR: './assets/img/user.jpg',
  DEFAULT_AVATAR_GROUP: './assets/img/user.jpg',
  DEFAULT_AVATAR_FB_PATH:
    'https://firebasestorage.googleapis.com/v0/b/dyspo-2bb43.appspot.com/o/avatarsStorage%2Fuser.jpg?alt=media&token=cd181d82-5b72-4392-bc2b-cecd8d3e6788',
  dyspo_email: 'appdyspo@gmail.com',
  BIOMETRIC_KEY: 'dyspo_123456',
  googleMapsApiKey: 'AIzaSyAnLbmH1fibqkFZ2nG3c4qgeNy1UQ4aG-8',
  firebase_avatar_storage_path: 'avatarsStorage/',
  firebase_avatar_group_storage_path: 'avatarGroupsStorage/',
  firebase_avatar_event_storage_path: 'avatarEventsStorage/',
  firebase_event_root: 'eventsMediaStorage/',
  messages_fetch_limit: 50,
  sendDebugData: false,
  cgu_url: 'https://dyspo.app/cgu.html',
  privacy_url: 'https://www.dyspo.app/charte-vie-privee.html',
  stores_url: 'https://dyspo.app/stores.html',
};
